using System.Reflection;
using System.Runtime.InteropServices;
using System.Web.UI;



[assembly: AssemblyTitle("IProc")]
[assembly: AssemblyDescription("Data Aquarium Framework application library")]
[assembly: AssemblyCompany("IProc")]
[assembly: AssemblyProduct("IProc Aquarium in the Box")]
[assembly: AssemblyCopyright("Copyright © IProc 2022")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: WebResource("IProc.js.sys._System.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.bootstrap.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.jquery-2.2.4.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.jquery-3.6.0.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.unicode.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf-odp.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf-ifttt.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.touch-input.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.input-blob.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.touch-edit.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf-resources.min.en_US.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.culture.en-US.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf-extensions.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.touch.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.touch-charts.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf-menu.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.MicrosoftAjax.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.MicrosoftAjaxWebForms.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.sys.AjaxControlToolkit.min.js", "text/javascript")]
[assembly: WebResource("IProc.js.daf.daf-membership.min.js", "text/javascript")]
[assembly: WebResource("IProc.Theme.Aquarium.css", "text/css", PerformSubstitution=true)]
[assembly: WebResource("IProc.Theme.Acrobat.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ActionBarBg.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ActionBarDiv.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ActionGroupBg.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.AddBookmark.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.AdvancedSearch.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.arrow-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.arrow-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ArrowBkg.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Attach.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Attention.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.BACK.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Calendar.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.CheckMark.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.CheckMark2.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.CheckMarkLarge.GIF", "image/GIF")]
[assembly: WebResource("IProc.Theme.Close.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.DataSheet.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Delete.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.DropArrow.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Edit.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.EditMode.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Erase.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Excel.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.EXCLAIM.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ExportCsv.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ExportRowset.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ExportRss.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Filter.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.FilterOff.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.FilterOffDisabled.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.FORWARD.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.HeaderBg.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.html-editor-buttons.png", "image/png")]
[assembly: WebResource("IProc.Theme.ICONGO.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Import.png", "image/png")]
[assembly: WebResource("IProc.Theme.Import2.png", "image/png")]
[assembly: WebResource("IProc.Theme.Information.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Maximize.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.MenuBg.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.MenuBgLarge.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Minimize.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.MultiPage.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Navigate.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.NavStrip.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.New.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.NewLarge.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ObjectRef.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Paste.png", "image/png")]
[assembly: WebResource("IProc.Theme.PopupArrow.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Print.png", "image/png")]
[assembly: WebResource("IProc.Theme.QuickFind.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Refresh.png", "image/png")]
[assembly: WebResource("IProc.Theme.Save.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.SaveLarge.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Search.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Search.png", "image/png")]
[assembly: WebResource("IProc.Theme.SearchPlusMinus.png", "image/png")]
[assembly: WebResource("IProc.Theme.SettingsGraphic.jpg", "image/jpg")]
[assembly: WebResource("IProc.Theme.SortAZ.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.SortDown.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.SortUp.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.SortZA.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.StatusBar.png", "image/png")]
[assembly: WebResource("IProc.Theme.syst-ui-bg_glass_65_ffffff_1x400.png", "image/png")]
[assembly: WebResource("IProc.Theme.syst-ui-icons_222222_256x240.png", "image/png")]
[assembly: WebResource("IProc.Theme.tab-active-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-left-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-right-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-active.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-active-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-active-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-active.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-hover-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-hover-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-hover.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-bottom.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-left-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-right-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-hover.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-left-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-left.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-line.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-right-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-right.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-verticalleft.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab-verticalright.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.tab.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.TabsActiveTab.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.TabsBar.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.TabsInactiveTab.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.TabsSelectedTab.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.TreeControls.png", "image/png")]
[assembly: WebResource("IProc.Theme.Undo.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.ViewNameBg.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Wait.gif", "image/gif")]
[assembly: WebResource("IProc.Theme.Word.gif", "image/gif")]
